# syntax=docker/dockerfile:1.2
FROM xingrz/venus-builder:latest

RUN apt-get install -y xinit libxrandr2 libxfixes3 libxcursor1

ENV DISPLAY=:0

ADD entrypoint-jlink.sh /
ENTRYPOINT [ "/entrypoint-jlink.sh" ]
